#!/bin/bash

docker build -t sonysantos/dropbox:latest .

if [ "$1" = "" ]; then
  echo "Created sonysantos/dropbox:latest!"
else
  docker tag sonysantos/dropbox:latest sonysantos/dropbox:$1
  echo "Created sonysantos/dropbox:$1 (latest)!"
fi
