#!/bin/bash

# check dropbox base directory
if [ "$1" == "" ]; then
  BASEDIR=$HOME
else
  BASEDIR=$1
fi

# check if dropbox paths already exist
if [[ -d "$BASEDIR/.dropbox" && -d "$BASEDIR/Dropbox" ]]; then
  # all ok, go to deamon
  OPTIONS="-d --name my-dropbox"
else
  # first run; initialize dirs and set interactive mode to link dropbox account
  mkdir $BASEDIR/.dropbox
  mkdir $BASEDIR/Dropbox
  OPTIONS="-it --rm"
fi

# run!

docker run $OPTIONS \
  -v $BASEDIR/Dropbox:/dbox/Dropbox \
  -v $BASEDIR/.dropbox:/dbox/.dropbox \
  -e DBOX_UID=`id -u` \
  -e DBOX_GID=`id -g` \
  sonysantos/dropbox:latest
