#!/bin/bash

if [ "$1" == "" ]; then
  BASEDIR=$HOME
else
  BASEDIR=$1
fi

docker run -d --name my-dropbox \
  -v $BASEDIR/Dropbox:/home/dbox/Dropbox \
  -v $BASEDIR/.dropbox:/home/dbox/.dropbox \
  -e DBOX_UID=`id -u` \
  -e DBOX_GID=`id -g` \
  sonysantos/dropbox:latest
